name: ecommerce_app
description: Flutter eCommerce app
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #General
  flutter_launcher_icons: 0.13.1
  go_router: 10.1.3
  flutter_riverpod: 2.4.6
  riverpod_annotation: 2.3.1
  rxdart: 0.27.7

  #DB
  sembast: 3.5.0+1
  sembast_web: 2.2.0
  path_provider: 2.1.1

  #UI
  flutter_layout_grid: 2.0.5
  flutter_rating_bar: 4.0.1
  shimmer: 3.0.0
  flutter_staggered_grid_view: 0.7.0
  cached_network_image: 3.3.0

  #Utils
  intl: 0.18.1
  collection: 1.18.0
  equatable: 2.0.5

  #Firebase
  firebase_core: 2.22.0
  firebase_auth: 4.14.0
  cloud_firestore: 4.13.1
  firebase_storage: 11.5.1

dev_dependencies:
  #Linters
  flutter_lints: 3.0.1
  custom_lint: 0.5.6

  #Tests
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.2
  firebase_auth_mocks: 0.13.0
  mock_exceptions: 0.8.2
  fake_cloud_firestore: 2.4.3
  firebase_storage_mocks: 0.6.1

  #Generators
  build_runner: 2.4.6
  riverpod_generator: 2.3.6

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  assets:
    - assets/products/
