// Mocks generated by Mockito 5.4.2 from annotations
// in ecommerce_app/test/src/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:ecommerce_app/src/features/authantication/data/fake_auth_repository.dart'
    as _i3;
import 'package:ecommerce_app/src/features/authantication/domain/app_user.dart'
    as _i7;
import 'package:ecommerce_app/src/features/cart/application/cart_service.dart'
    as _i8;
import 'package:ecommerce_app/src/features/cart/data/local/local_cart_repository.dart'
    as _i4;
import 'package:ecommerce_app/src/features/cart/data/remote/remote_cart_repository.dart'
    as _i5;
import 'package:ecommerce_app/src/features/cart/domain/cart.dart' as _i2;
import 'package:ecommerce_app/src/features/cart/domain/item.dart' as _i9;
import 'package:ecommerce_app/src/features/products/data/fake_products_repository.dart'
    as _i10;
import 'package:ecommerce_app/src/features/products/domain/product.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCart_0 extends _i1.SmartFake implements _i2.Cart {
  _FakeCart_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFakeAuthRepository_1 extends _i1.SmartFake
    implements _i3.FakeAuthRepository {
  _FakeFakeAuthRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLocalCartRepository_2 extends _i1.SmartFake
    implements _i4.LocalCartRepository {
  _FakeLocalCartRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRemoteCartRepository_3 extends _i1.SmartFake
    implements _i5.RemoteCartRepository {
  _FakeRemoteCartRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FakeAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeAuthRepository extends _i1.Mock
    implements _i3.FakeAuthRepository {
  MockFakeAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get addDelay => (super.noSuchMethod(
        Invocation.getter(#addDelay),
        returnValue: false,
      ) as bool);

  @override
  _i6.Stream<_i7.AppUser?> authStateChanges() => (super.noSuchMethod(
        Invocation.method(
          #authStateChanges,
          [],
        ),
        returnValue: _i6.Stream<_i7.AppUser?>.empty(),
      ) as _i6.Stream<_i7.AppUser?>);

  @override
  _i6.Future<void> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [RemoteCartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteCartRepository extends _i1.Mock
    implements _i5.RemoteCartRepository {
  MockRemoteCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Cart> fetchCart(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #fetchCart,
          [uid],
        ),
        returnValue: _i6.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #fetchCart,
            [uid],
          ),
        )),
      ) as _i6.Future<_i2.Cart>);

  @override
  _i6.Stream<_i2.Cart> watchCart(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #watchCart,
          [uid],
        ),
        returnValue: _i6.Stream<_i2.Cart>.empty(),
      ) as _i6.Stream<_i2.Cart>);

  @override
  _i6.Future<void> setCart(
    String? uid,
    _i2.Cart? cart,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setCart,
          [
            uid,
            cart,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [LocalCartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCartRepository extends _i1.Mock
    implements _i4.LocalCartRepository {
  MockLocalCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Cart> fetchCart() => (super.noSuchMethod(
        Invocation.method(
          #fetchCart,
          [],
        ),
        returnValue: _i6.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #fetchCart,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Cart>);

  @override
  _i6.Stream<_i2.Cart> watchCart() => (super.noSuchMethod(
        Invocation.method(
          #watchCart,
          [],
        ),
        returnValue: _i6.Stream<_i2.Cart>.empty(),
      ) as _i6.Stream<_i2.Cart>);

  @override
  _i6.Future<void> setCart(_i2.Cart? cart) => (super.noSuchMethod(
        Invocation.method(
          #setCart,
          [cart],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i8.CartService {
  MockCartService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FakeAuthRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeFakeAuthRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.FakeAuthRepository);

  @override
  _i4.LocalCartRepository get localCartRepository => (super.noSuchMethod(
        Invocation.getter(#localCartRepository),
        returnValue: _FakeLocalCartRepository_2(
          this,
          Invocation.getter(#localCartRepository),
        ),
      ) as _i4.LocalCartRepository);

  @override
  _i5.RemoteCartRepository get remoteCartRepository => (super.noSuchMethod(
        Invocation.getter(#remoteCartRepository),
        returnValue: _FakeRemoteCartRepository_3(
          this,
          Invocation.getter(#remoteCartRepository),
        ),
      ) as _i5.RemoteCartRepository);

  @override
  _i6.Future<void> setItem(_i9.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #setItem,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addItem(_i9.Item? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeItemById(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #removeItemById,
          [productId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [FakeProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeProductsRepository extends _i1.Mock
    implements _i10.FakeProductsRepository {
  MockFakeProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get addDelay => (super.noSuchMethod(
        Invocation.getter(#addDelay),
        returnValue: false,
      ) as bool);

  @override
  List<_i11.Product> getProductList() => (super.noSuchMethod(
        Invocation.method(
          #getProductList,
          [],
        ),
        returnValue: <_i11.Product>[],
      ) as List<_i11.Product>);

  @override
  _i11.Product? getProduct(String? id) => (super.noSuchMethod(Invocation.method(
        #getProduct,
        [id],
      )) as _i11.Product?);

  @override
  _i6.Future<List<_i11.Product>> fetchProductList() => (super.noSuchMethod(
        Invocation.method(
          #fetchProductList,
          [],
        ),
        returnValue: _i6.Future<List<_i11.Product>>.value(<_i11.Product>[]),
      ) as _i6.Future<List<_i11.Product>>);

  @override
  _i6.Stream<List<_i11.Product>> watchProductList() => (super.noSuchMethod(
        Invocation.method(
          #watchProductList,
          [],
        ),
        returnValue: _i6.Stream<List<_i11.Product>>.empty(),
      ) as _i6.Stream<List<_i11.Product>>);

  @override
  _i6.Stream<_i11.Product?> watchProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #watchProduct,
          [id],
        ),
        returnValue: _i6.Stream<_i11.Product?>.empty(),
      ) as _i6.Stream<_i11.Product?>);
}
